### ISSUE TITLE
Is there a userdata example

### ISSUE THREAD

**Issue by marriusco** [matusnovak/simplesquirrel#5]
Hi,

- I cannot figure out how to return a userdata or user pointer to script. Sqrat lack of this mapping too.
- Will  table  support any iteration like Sqrat in the future
-Thank you

Thank you.

**Comment by matusnovak** [comment]
Hi there. 

If you are referring to functions such as `sq_setinstanceup`, those are used by SimpleSquirrel to set internal data (things such as passing around a pointer to a class which a Squirrel instance needs to keep track of). Overwriting them may cause segmentation fault. I believe Sqrat uses them in a similar way.

I would advise to use a custom C++ class, that will contain the data you need to pass around, bind it with this library, and use that instead of userdata/user pointers.

As for the table iteration, I haven't updated this library in a while, and I am already occupied by other things at the moment. I do not plan on implementing that, sorry. If you happen to implement it, I am happy to review and accept a pull request.

**Comment by marriusco** [comment]
Hi,
That;s what I did, a Buffer class, passing pointers to allocated data around.
I will have a look into the enumeration of a table as well. Thx
Thank you.
